server:
  port: 7009
spring:
  application:
    name: tensquare-sms #指定服务名
  rabbitmq:
      host: 192.168.11.128
aliyun:
  sms:
    accessKeyId: 11
    accessKeySecret: 11
    template_code: 11
    sign_name: 11