server:
  port: 7006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.11.128
      database: spitdb
  redis:
    host: 192.168.11.128
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true